### PR TITLE
update for gjf v1.8

### PR DESCRIPTION
**Pull request by shua**
- update google-java-format dependency to version 1.8
- JavadocOnlyImports was removed, so remove reference to it
- reorderImports(String) is deprecated, use recommended reorderImports(String, Style)
- build still failing due to some maven-plugin-plugin errors I didn't understand, but updating the plugin version seemed to fix it, anything else I tried didn't

### CODE REVIEW

**Comment by shua** [comment]
example of maven-plugin-plugin errors:
```
[INFO] --- maven-plugin-plugin:3.5:descriptor (default-descriptor) @ fmt-maven-plugin ---
[INFO] Using 'UTF-8' encoding to read mojo source files.
[INFO] java-javadoc mojo extractor found 0 mojo descriptor.
[ERROR] Failed to analyze /Users/jllore467/.m2/repository/com/google/googlejavaformat/google-java-format/1.8/google-java-format-1.8.jar!/com/google/googlejavaformat/CommentsHelper.class
```

**Comment by shua** [comment]
cc @malaporte because I see you reviewed/merged the last upgrade PR

**Comment by shua** [comment]
it seems travis is broken, as it failed to simply download the jdk

**Comment by ericbn** [comment]
@shua, looks like "oraclejdk8" is not supported anymore by Travis. And also the minimum supported runtime version for google-java-format 1.8 is now JDK 11, so you might need to update the `.travis.yml` file with:

```
jdk:
- openjdk11
```

**Comment by shua** [comment]
Thanks @ericbn looks like that worked. cc @malaporte again, as this PR is ready to merge.

**Comment by shua** [comment]
@malaporte (thank you for this project)
image

**Comment by malaporte** [comment]
HAHAHAHA ok so this definitively got my attention. Sorry - I've been neglecting my GitHub notifications somewhat lately. I'll publish a new release right away.

**Pull request merged**
